name : sal Custom Action CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World custom action
        uses: SMAN04/custom_actions@main
        with:
          who to greet: "Sal"